-- ═══════════════════════════════════════════════════════════
-- Eaty v0.6.2 — AC1 補照片（2026-10-05）
-- 54 道缺照片的菜品，統一補上所屬分類的官方圖片
-- （與官方點餐站做法一致：分類圖就是該檔口卡片的照片）
-- 圖片已存 repo assets/ac1/cat-*.jpg，可重複執行。
-- ═══════════════════════════════════════════════════════════

update dishes d set photo = v.photo from (values
('ac1-lemongrass-wing-duo-fun', 'assets/ac1/cat-thai-fun.jpg'),
('ac1-lemongrass-porkchop-duo-fun', 'assets/ac1/cat-thai-fun.jpg'),
('ac1-lemongrass-porkchop-fun', 'assets/ac1/cat-thai-fun.jpg'),
('ac1-lemongrass-wing-fun', 'assets/ac1/cat-thai-fun.jpg'),
('ac1-a-la-carte-dish', 'assets/ac1/cat-a-la-carte.jpg'),
('ac1-chinese-soup', 'assets/ac1/cat-a-la-carte.jpg'),
('ac1-steamed-rice', 'assets/ac1/cat-a-la-carte.jpg'),
('ac1-minced-noodle-soup', 'assets/ac1/cat-minced-noodle.jpg'),
('ac1-minced-noodle-spicy', 'assets/ac1/cat-minced-noodle.jpg'),
('ac1-beef-noodle', 'assets/ac1/cat-taiwanese-soup-noodle.jpg'),
('ac1-beef-noodle-2', 'assets/ac1/cat-taiwanese-soup-noodle.jpg'),
('ac1-suanla-mixian', 'assets/ac1/cat-spicy-mixian.jpg'),
('ac1-hot-sour-mixian-dish', 'assets/ac1/cat-spicy-mixian.jpg'),
('ac1-thai-chicken', 'assets/ac1/cat-thai-picks.jpg'),
('ac1-lemongrass-leg', 'assets/ac1/cat-thai-picks.jpg'),
('ac1-beef-duo-fun', 'assets/ac1/cat-thai-fun.jpg'),
('ac1-beef-fun', 'assets/ac1/cat-thai-fun.jpg'),
('ac1-fishball-fun', 'assets/ac1/cat-thai-fun.jpg'),
('ac1-roast-meats-dish', 'assets/ac1/cat-roast-meats.jpg'),
('ac1-roast-meats-dish-2', 'assets/ac1/cat-roast-meats.jpg'),
('ac1-roast-meats-dish-3', 'assets/ac1/cat-roast-meats.jpg'),
('ac1-roast-recommend-dish', 'assets/ac1/cat-roast-recommend.jpg'),
('ac1-roast-recommend-dish-2', 'assets/ac1/cat-roast-recommend.jpg'),
('ac1-roast-recommend-dish-3', 'assets/ac1/cat-roast-recommend.jpg'),
('ac1-roast-select-dish', 'assets/ac1/cat-roast-select.jpg'),
('ac1-castle-fried-chicken-dish', 'assets/ac1/cat-castle-fried-chicken.jpg'),
('ac1-castle-fried-chicken-dish-2', 'assets/ac1/cat-castle-fried-chicken.jpg'),
('ac1-castle-fried-chicken-dish-3', 'assets/ac1/cat-castle-fried-chicken.jpg'),
('ac1-castle-fried-chicken-2', 'assets/ac1/cat-castle-fried-chicken.jpg'),
('ac1-pepperoni', 'assets/ac1/cat-pizza.jpg'),
('ac1-cha-lau-fan', 'assets/ac1/cat-value-roast-rice.jpg'),
('ac1-thai-fishcake', 'assets/ac1/cat-value-roast-rice.jpg'),
('ac1-value-roast-rice-dish', 'assets/ac1/cat-value-roast-rice.jpg'),
('ac1-pork-chop-bun-set-10--15', 'assets/ac1/cat-porkchop-bun.jpg'),
('ac1-pork-chop-bun-set-10--15-2', 'assets/ac1/cat-porkchop-bun.jpg'),
('ac1-pork-chop-bun-set-10--15-5', 'assets/ac1/cat-porkchop-bun.jpg'),
('ac1-pork-chop-bun-set-10--15-6', 'assets/ac1/cat-porkchop-bun.jpg'),
('ac1-chicken-leg-set-dish', 'assets/ac1/cat-chicken-leg.jpg'),
('ac1-chicken-leg-set-dish-2', 'assets/ac1/cat-chicken-leg.jpg'),
('ac1-chicken-leg-set-dish-3', 'assets/ac1/cat-chicken-leg.jpg'),
('ac1-chicken-leg-set-dish-4', 'assets/ac1/cat-chicken-leg.jpg'),
('ac1-chicken-leg-set-dish-5', 'assets/ac1/cat-chicken-leg.jpg'),
('ac1-chicken-leg-set-dish-6', 'assets/ac1/cat-chicken-leg.jpg'),
('ac1-chicken-leg-set-dish-7', 'assets/ac1/cat-chicken-leg.jpg'),
('ac1-chicken-leg-set-dish-8', 'assets/ac1/cat-chicken-leg.jpg'),
('ac1-chicken-leg-set-dish-9', 'assets/ac1/cat-chicken-leg.jpg'),
('ac1-street-bowl-soup-dish', 'assets/ac1/cat-street-bowl.jpg'),
('ac1-street-bowl-soup-dish-2', 'assets/ac1/cat-street-bowl.jpg'),
('ac1-street-bowl-soup-dish-3', 'assets/ac1/cat-street-bowl.jpg'),
('ac1-street-bowl-soup-dish-4', 'assets/ac1/cat-street-bowl.jpg'),
('ac1-french-toast', 'assets/ac1/cat-french-toast.jpg'),
('ac1-coffee-lounge-12oz-15', 'assets/ac1/cat-coffee-lounge.jpg'),
('ac1-coffee-lounge-dish', 'assets/ac1/cat-coffee-lounge.jpg'),
('ac1-white-pepper-chicken-rice', 'assets/ac1/cat-roast-recommend.jpg')
) as v(id, photo) where d.id = v.id;
